In [113]:

import numpy as np


#.in files
X = np.array([[14,20],[16,3],[24,30],[11,62],[30,-4]])
pwrZ = np.ones((len(X),1))
X = np.hstack((pwrZ,X))
y = np.array([[69],[-1],[99],[240],[-43]])

print("X =",X)
print("y =",y)

X = [[1.0000 14.0000 20.0000]
 [1.0000 16.0000 3.0000]
 [1.0000 24.0000 30.0000]
 [1.0000 11.0000 62.0000]
 [1.0000 30.0000 -4.0000]]
y = [[ 69]
 [ -1]
 [ 99]
 [240]
 [-43]]


In [110]:
def Analytical(X,y):
    XT = np.transpose(X)
    Xinv = np.linalg.inv(XT.dot(X))
    W = (Xinv.dot(XT)).dot(y)
    float_formatter = "{:.4f}".format
    np.set_printoptions(formatter={'float_kind':float_formatter})
    print(W)
    return(W)
    
Analytical(X,y)

[[3.0000]
 [-1.0000]
 [4.0000]]


array([[3.0000],
       [-1.0000],
       [4.0000]])

In [111]:
#Json files
#number of iterations
T = 100000
#learning rate
Lrate = 0.0001

In [112]:
def GD(iters, rate, XG, yG, guess = ([[1],[1],[1]])):
    w = guess
    N = yG.shape[0]
    
    for _ in range(iters):
        temp = XG.dot(w)-yG
        temp = np.dot(X.T, temp)
        w = w-((rate/N)*temp)
    
    float_formatter = "{:.4f}".format
    np.set_printoptions(formatter={'float_kind':float_formatter})
    print(w)
    return w

GD(T,Lrate,X,y)

[[1.7745]
 [-0.9521]
 [4.0114]]


array([[1.7745],
       [-0.9521],
       [4.0114]])